openapi: "3.0.0"
info:
  version: 1.0.0
  title: Musical Enigma
servers:
  - url: http://localhost:3333
paths:
  /music:
    get:
      summary: List all music
      tags:
        - music
      parameters:
        - name: genre
          in: query
          description: Filter results by genre
          required: true
          schema:
            type: string
        - name: artist
          in: query
          description: Filter results by artist
          required: true
          schema:
            type: string
      responses:
        '200':
          description: An empty object
